// ============================================================
// 1. ОБЪЯВЛЕНИЕ ВЕРСИИ ПРОТОКОЛА
// ============================================================
// proto3 — это язык описания данных, который понимают все языки программирования.
// Он не зависит от Go, Kotlin, Java, Python, C++ и т.д.
//
// proto2 — старая версия, proto3 — текущая (используется везде).
// Разница: в proto3 все поля опциональны по умолчанию, в proto2 нужно явно указывать.
//
// !!! ВАЖНО: эту строку НЕЛЬЗЯ менять — она определяет синтаксис, который будет использоваться.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/subscription.proto

// ============================================================
// 2. ПАКЕТ (пространство имён)
// ============================================================
// Пакет — это как namespace в других языках.
// Он нужен, чтобы избежать конфликтов, если в проекте будет несколько .proto-файлов.
//
// Например, если у нас будет ещё один сервис для "Пользователей" — его пакет будет user.
// Тогда subscription.Subscription и user.Subscription — это разные типы.
//
// !!! ВАЖНО: пакет используется в сгенерированном коде как префикс для типов.

package subscription

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================
// 4. ПУСТОЕ СООБЩЕНИЕ (Empty)
// ============================================================
// В gRPC каждый метод должен принимать и возвращать какое-то сообщение.
// Но иногда нужно вернуть "ничего" (например, при успешном удалении).
//
// Empty — это "пустышка". В нём нет полей, только заголовок.
// Используется для методов, которые не возвращают данных, но должны что-то вернуть,
// чтобы удовлетворить синтаксис gRPC.
//
// Аналог в REST: HTTP 204 No Content.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{0}
}

// Subscription — полное описание одной подписки.
// Совпадает с models.Subscription в Go и Subscription в Kotlin.
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // ID подписки (генерируется БД)
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Название сервиса (из шаблона)
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                               // Цена (из шаблона)
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // UUID пользователя
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`       // Дата начала (MM-YYYY)
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`             // Дата окончания (MM-YYYY), может быть пустой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Subscription) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Subscription) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// SubscriptionList — список подписок.
// Используется как ответ на GetSubscriptions.
type SubscriptionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"` // repeated = массив (в Go это []Subscription)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionList) Reset() {
	*x = SubscriptionList{}
	mi := &file_proto_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionList) ProtoMessage() {}

func (x *SubscriptionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionList.ProtoReflect.Descriptor instead.
func (*SubscriptionList) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionList) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// CreateRequest — запрос на создание подписки.
// Отличается от Subscription тем, что ID не передаётся (генерируется БД).
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    int32                  `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // ID шаблона (обязательно)
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // UUID пользователя (берётся из JWT)
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`     // Дата начала (обязательно, MM-YYYY)
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`           // Дата окончания (опционально, MM-YYYY)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *CreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// UpdateRequest — запрос на обновление подписки.
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // ID подписки (обязательно)
	TemplateId    int32                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // Новый ID шаблона
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // UUID пользователя
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`     // Новая дата начала
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`           // Новая дата окончания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *UpdateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// GetRequest — запрос по ID (используется в GetSubscription и DeleteSubscription).
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CreateResponse — ответ на создание (возвращает ID).
type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID созданной записи
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetSubscriptionsRequest — запрос на список подписок с пагинацией.
type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // Сколько записей вернуть (по умолчанию 20)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Сдвиг от начала (по умолчанию 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_proto_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *GetSubscriptionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSubscriptionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// TotalCostRequest — запрос на расчёт суммы.
type TotalCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // ID пользователя (опционально, если пусто — все)
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Название сервиса (опционально, если пусто — все)
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`       // Дата начала (обязательно, MM-YYYY)
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`             // Дата окончания (обязательно, MM-YYYY)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalCostRequest) Reset() {
	*x = TotalCostRequest{}
	mi := &file_proto_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalCostRequest) ProtoMessage() {}

func (x *TotalCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalCostRequest.ProtoReflect.Descriptor instead.
func (*TotalCostRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *TotalCostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TotalCostRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TotalCostRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TotalCostRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// TotalCostResponse — ответ с суммой.
type TotalCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // Суммарная стоимость в рублях
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalCostResponse) Reset() {
	*x = TotalCostResponse{}
	mi := &file_proto_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalCostResponse) ProtoMessage() {}

func (x *TotalCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalCostResponse.ProtoReflect.Descriptor instead.
func (*TotalCostResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *TotalCostResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Template — шаблон подписки.
type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // ID шаблона
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Название сервиса
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                               // Цена (в рублях)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_proto_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *Template) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Template) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Template) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// TemplateList — список шаблонов.
type TemplateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateList) Reset() {
	*x = TemplateList{}
	mi := &file_proto_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateList) ProtoMessage() {}

func (x *TemplateList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateList.ProtoReflect.Descriptor instead.
func (*TemplateList) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateList) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

// CreateTemplateRequest — запрос на создание шаблона.
type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Название (обязательно)
	Price         int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`                               // Цена (обязательно, >= 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_proto_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTemplateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateTemplateRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// UpdateTemplateRequest — запрос на обновление шаблона.
type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // ID шаблона (обязательно)
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Новое название
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                               // Новая цена
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_proto_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTemplateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTemplateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UpdateTemplateRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_proto_rawDesc = "" +
	"\n" +
	"\x18proto/subscription.proto\x12\fsubscription\"\a\n" +
	"\x05Empty\"\xaa\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\"T\n" +
	"\x10SubscriptionList\x12@\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1a.subscription.SubscriptionR\rsubscriptions\"\x83\x01\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x05R\n" +
	"templateId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\x93\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x05R\n" +
	"templateId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"G\n" +
	"\x17GetSubscriptionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x88\x01\n" +
	"\x10TotalCostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\")\n" +
	"\x11TotalCostResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"S\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"D\n" +
	"\fTemplateList\x124\n" +
	"\ttemplates\x18\x01 \x03(\v2\x16.subscription.TemplateR\ttemplates\"P\n" +
	"\x15CreateTemplateRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\"`\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price2\xcd\x06\n" +
	"\x13SubscriptionService\x12Y\n" +
	"\x10GetSubscriptions\x12%.subscription.GetSubscriptionsRequest\x1a\x1e.subscription.SubscriptionList\x12O\n" +
	"\x12CreateSubscription\x12\x1b.subscription.CreateRequest\x1a\x1c.subscription.CreateResponse\x12G\n" +
	"\x0fGetSubscription\x12\x18.subscription.GetRequest\x1a\x1a.subscription.Subscription\x12F\n" +
	"\x12UpdateSubscription\x12\x1b.subscription.UpdateRequest\x1a\x13.subscription.Empty\x12C\n" +
	"\x12DeleteSubscription\x12\x18.subscription.GetRequest\x1a\x13.subscription.Empty\x12O\n" +
	"\fGetTotalCost\x12\x1e.subscription.TotalCostRequest\x1a\x1f.subscription.TotalCostResponse\x12@\n" +
	"\rListTemplates\x12\x13.subscription.Empty\x1a\x1a.subscription.TemplateList\x12?\n" +
	"\vGetTemplate\x12\x18.subscription.GetRequest\x1a\x16.subscription.Template\x12S\n" +
	"\x0eCreateTemplate\x12#.subscription.CreateTemplateRequest\x1a\x1c.subscription.CreateResponse\x12J\n" +
	"\x0eUpdateTemplate\x12#.subscription.UpdateTemplateRequest\x1a\x13.subscription.Empty\x12?\n" +
	"\x0eDeleteTemplate\x12\x18.subscription.GetRequest\x1a\x13.subscription.EmptyB\x14Z\x12proto/subscriptionb\x06proto3"

var (
	file_proto_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_proto_rawDescData []byte
)

func file_proto_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_proto_rawDesc), len(file_proto_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_proto_rawDescData
}

var file_proto_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_subscription_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: subscription.Empty
	(*Subscription)(nil),            // 1: subscription.Subscription
	(*SubscriptionList)(nil),        // 2: subscription.SubscriptionList
	(*CreateRequest)(nil),           // 3: subscription.CreateRequest
	(*UpdateRequest)(nil),           // 4: subscription.UpdateRequest
	(*GetRequest)(nil),              // 5: subscription.GetRequest
	(*CreateResponse)(nil),          // 6: subscription.CreateResponse
	(*GetSubscriptionsRequest)(nil), // 7: subscription.GetSubscriptionsRequest
	(*TotalCostRequest)(nil),        // 8: subscription.TotalCostRequest
	(*TotalCostResponse)(nil),       // 9: subscription.TotalCostResponse
	(*Template)(nil),                // 10: subscription.Template
	(*TemplateList)(nil),            // 11: subscription.TemplateList
	(*CreateTemplateRequest)(nil),   // 12: subscription.CreateTemplateRequest
	(*UpdateTemplateRequest)(nil),   // 13: subscription.UpdateTemplateRequest
}
var file_proto_subscription_proto_depIdxs = []int32{
	1,  // 0: subscription.SubscriptionList.subscriptions:type_name -> subscription.Subscription
	10, // 1: subscription.TemplateList.templates:type_name -> subscription.Template
	7,  // 2: subscription.SubscriptionService.GetSubscriptions:input_type -> subscription.GetSubscriptionsRequest
	3,  // 3: subscription.SubscriptionService.CreateSubscription:input_type -> subscription.CreateRequest
	5,  // 4: subscription.SubscriptionService.GetSubscription:input_type -> subscription.GetRequest
	4,  // 5: subscription.SubscriptionService.UpdateSubscription:input_type -> subscription.UpdateRequest
	5,  // 6: subscription.SubscriptionService.DeleteSubscription:input_type -> subscription.GetRequest
	8,  // 7: subscription.SubscriptionService.GetTotalCost:input_type -> subscription.TotalCostRequest
	0,  // 8: subscription.SubscriptionService.ListTemplates:input_type -> subscription.Empty
	5,  // 9: subscription.SubscriptionService.GetTemplate:input_type -> subscription.GetRequest
	12, // 10: subscription.SubscriptionService.CreateTemplate:input_type -> subscription.CreateTemplateRequest
	13, // 11: subscription.SubscriptionService.UpdateTemplate:input_type -> subscription.UpdateTemplateRequest
	5,  // 12: subscription.SubscriptionService.DeleteTemplate:input_type -> subscription.GetRequest
	2,  // 13: subscription.SubscriptionService.GetSubscriptions:output_type -> subscription.SubscriptionList
	6,  // 14: subscription.SubscriptionService.CreateSubscription:output_type -> subscription.CreateResponse
	1,  // 15: subscription.SubscriptionService.GetSubscription:output_type -> subscription.Subscription
	0,  // 16: subscription.SubscriptionService.UpdateSubscription:output_type -> subscription.Empty
	0,  // 17: subscription.SubscriptionService.DeleteSubscription:output_type -> subscription.Empty
	9,  // 18: subscription.SubscriptionService.GetTotalCost:output_type -> subscription.TotalCostResponse
	11, // 19: subscription.SubscriptionService.ListTemplates:output_type -> subscription.TemplateList
	10, // 20: subscription.SubscriptionService.GetTemplate:output_type -> subscription.Template
	6,  // 21: subscription.SubscriptionService.CreateTemplate:output_type -> subscription.CreateResponse
	0,  // 22: subscription.SubscriptionService.UpdateTemplate:output_type -> subscription.Empty
	0,  // 23: subscription.SubscriptionService.DeleteTemplate:output_type -> subscription.Empty
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_subscription_proto_init() }
func file_proto_subscription_proto_init() {
	if File_proto_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_proto_rawDesc), len(file_proto_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_proto_depIdxs,
		MessageInfos:      file_proto_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_proto = out.File
	file_proto_subscription_proto_goTypes = nil
	file_proto_subscription_proto_depIdxs = nil
}
