// ============================================================
// 1. ВЕРСИЯ ПРОТОКОЛА
// ============================================================
// proto3 — текущая стабильная версия, используется везде.
// proto2 — старая, не используй.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: proto/subscription.proto

// ============================================================
// 2. ПАКЕТ (пространство имён)
// ============================================================
// Нужен, чтобы избежать конфликтов, если будет несколько .proto-файлов.
// Обычно совпадает с названием сервиса.

package subscription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SubscriptionService_GetSubscriptions_FullMethodName   = "/subscription.SubscriptionService/GetSubscriptions"
	SubscriptionService_CreateSubscription_FullMethodName = "/subscription.SubscriptionService/CreateSubscription"
	SubscriptionService_GetSubscription_FullMethodName    = "/subscription.SubscriptionService/GetSubscription"
	SubscriptionService_UpdateSubscription_FullMethodName = "/subscription.SubscriptionService/UpdateSubscription"
	SubscriptionService_DeleteSubscription_FullMethodName = "/subscription.SubscriptionService/DeleteSubscription"
	SubscriptionService_GetTotalCost_FullMethodName       = "/subscription.SubscriptionService/GetTotalCost"
)

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	// -------- 4.1. ПОЛУЧИТЬ ВСЕ ПОДПИСКИ (аналог GET /subscriptions) --------
	// На вход: запрос (пагинация и офсет).
	// На выход: список подписок.
	GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionList, error)
	// -------- 4.2. СОЗДАТЬ ПОДПИСКУ (аналог POST /subscriptions) --------
	// На вход: данные новой подписки.
	// На выход: ID созданной записи.
	CreateSubscription(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// -------- 4.3. ПОЛУЧИТЬ ОДНУ ПОДПИСКУ ПО ID (аналог GET /subscriptions/{id}) --
	// На вход: ID.
	// На выход: полная запись подписки.
	GetSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Subscription, error)
	// -------- 4.4. ОБНОВИТЬ ПОДПИСКУ (аналог PUT /subscriptions/{id}) ----------
	// На вход: ID + новые данные.
	// На выход: ничего (Empty).
	UpdateSubscription(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	// -------- 4.5. УДАЛИТЬ ПОДПИСКУ (аналог DELETE /subscriptions/{id}) --------
	// На вход: ID.
	// На выход: ничего (Empty).
	DeleteSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Empty, error)
	// -------- 4.6. СУММАРНАЯ СТОИМОСТЬ (аналог GET /subscriptions/total-cost) --
	// На вход: фильтры (user_id, service_name, start_date, end_date).
	// На выход: сумма (total).
	GetTotalCost(ctx context.Context, in *TotalCostRequest, opts ...grpc.CallOption) (*TotalCostResponse, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionList, error) {
	out := new(SubscriptionList)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CreateSubscription(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CreateSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Subscription, error) {
	out := new(Subscription)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) UpdateSubscription(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubscriptionService_UpdateSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) DeleteSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubscriptionService_DeleteSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetTotalCost(ctx context.Context, in *TotalCostRequest, opts ...grpc.CallOption) (*TotalCostResponse, error) {
	out := new(TotalCostResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetTotalCost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	// -------- 4.1. ПОЛУЧИТЬ ВСЕ ПОДПИСКИ (аналог GET /subscriptions) --------
	// На вход: запрос (пагинация и офсет).
	// На выход: список подписок.
	GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*SubscriptionList, error)
	// -------- 4.2. СОЗДАТЬ ПОДПИСКУ (аналог POST /subscriptions) --------
	// На вход: данные новой подписки.
	// На выход: ID созданной записи.
	CreateSubscription(context.Context, *CreateRequest) (*CreateResponse, error)
	// -------- 4.3. ПОЛУЧИТЬ ОДНУ ПОДПИСКУ ПО ID (аналог GET /subscriptions/{id}) --
	// На вход: ID.
	// На выход: полная запись подписки.
	GetSubscription(context.Context, *GetRequest) (*Subscription, error)
	// -------- 4.4. ОБНОВИТЬ ПОДПИСКУ (аналог PUT /subscriptions/{id}) ----------
	// На вход: ID + новые данные.
	// На выход: ничего (Empty).
	UpdateSubscription(context.Context, *UpdateRequest) (*Empty, error)
	// -------- 4.5. УДАЛИТЬ ПОДПИСКУ (аналог DELETE /subscriptions/{id}) --------
	// На вход: ID.
	// На выход: ничего (Empty).
	DeleteSubscription(context.Context, *GetRequest) (*Empty, error)
	// -------- 4.6. СУММАРНАЯ СТОИМОСТЬ (аналог GET /subscriptions/total-cost) --
	// На вход: фильтры (user_id, service_name, start_date, end_date).
	// На выход: сумма (total).
	GetTotalCost(context.Context, *TotalCostRequest) (*TotalCostResponse, error)
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*SubscriptionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedSubscriptionServiceServer) CreateSubscription(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetSubscription(context.Context, *GetRequest) (*Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) UpdateSubscription(context.Context, *UpdateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) DeleteSubscription(context.Context, *GetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetTotalCost(context.Context, *TotalCostRequest) (*TotalCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalCost not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetSubscriptions(ctx, req.(*GetSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CreateSubscription(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetSubscription(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).UpdateSubscription(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).DeleteSubscription(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetTotalCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetTotalCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetTotalCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetTotalCost(ctx, req.(*TotalCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriptions",
			Handler:    _SubscriptionService_GetSubscriptions_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _SubscriptionService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _SubscriptionService_GetSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _SubscriptionService_UpdateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _SubscriptionService_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetTotalCost",
			Handler:    _SubscriptionService_GetTotalCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/subscription.proto",
}
