// ============================================================
// 1. ОБЪЯВЛЕНИЕ ВЕРСИИ ПРОТОКОЛА
// ============================================================
// proto3 — это язык описания данных, который понимают все языки программирования.
// Он не зависит от Go, Kotlin, Java, Python, C++ и т.д.
//
// proto2 — старая версия, proto3 — текущая (используется везде).
// Разница: в proto3 все поля опциональны по умолчанию, в proto2 нужно явно указывать.
//
// !!! ВАЖНО: эту строку НЕЛЬЗЯ менять — она определяет синтаксис, который будет использоваться.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: proto/subscription.proto

// ============================================================
// 2. ПАКЕТ (пространство имён)
// ============================================================
// Пакет — это как namespace в других языках.
// Он нужен, чтобы избежать конфликтов, если в проекте будет несколько .proto-файлов.
//
// Например, если у нас будет ещё один сервис для "Пользователей" — его пакет будет user.
// Тогда subscription.Subscription и user.Subscription — это разные типы.
//
// !!! ВАЖНО: пакет используется в сгенерированном коде как префикс для типов.

package subscription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SubscriptionService_GetSubscriptions_FullMethodName   = "/subscription.SubscriptionService/GetSubscriptions"
	SubscriptionService_CreateSubscription_FullMethodName = "/subscription.SubscriptionService/CreateSubscription"
	SubscriptionService_GetSubscription_FullMethodName    = "/subscription.SubscriptionService/GetSubscription"
	SubscriptionService_UpdateSubscription_FullMethodName = "/subscription.SubscriptionService/UpdateSubscription"
	SubscriptionService_DeleteSubscription_FullMethodName = "/subscription.SubscriptionService/DeleteSubscription"
	SubscriptionService_GetTotalCost_FullMethodName       = "/subscription.SubscriptionService/GetTotalCost"
	SubscriptionService_ListTemplates_FullMethodName      = "/subscription.SubscriptionService/ListTemplates"
	SubscriptionService_GetTemplate_FullMethodName        = "/subscription.SubscriptionService/GetTemplate"
	SubscriptionService_CreateTemplate_FullMethodName     = "/subscription.SubscriptionService/CreateTemplate"
	SubscriptionService_UpdateTemplate_FullMethodName     = "/subscription.SubscriptionService/UpdateTemplate"
	SubscriptionService_DeleteTemplate_FullMethodName     = "/subscription.SubscriptionService/DeleteTemplate"
)

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	// --- GET /api/subscriptions ---
	// Получить список всех подписок (с пагинацией).
	// На вход: limit (сколько записей), offset (сдвиг от начала).
	// На выход: список подписок (SubscriptionList).
	//
	// В REST это выглядит так:
	//
	//	GET /api/subscriptions?limit=10&offset=0
	GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionList, error)
	// --- POST /api/subscriptions ---
	// Создать новую подписку.
	// На вход: template_id, user_id, start_date, end_date.
	// На выход: ID созданной подписки.
	//
	// В REST это выглядит так:
	//
	//	POST /api/subscriptions
	//	Body: { "template_id": 1, "user_id": "...", "start_date": "08-2025", "end_date": "..." }
	CreateSubscription(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// --- GET /api/subscriptions/{id} ---
	// Получить одну подписку по её ID.
	// На вход: id.
	// На выход: полная запись подписки (Subscription).
	//
	// В REST это выглядит так:
	//
	//	GET /api/subscriptions/5
	GetSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Subscription, error)
	// --- PUT /api/subscriptions/{id} ---
	// Обновить существующую подписку.
	// На вход: id + новые поля.
	// На выход: ничего (Empty), только статус успеха.
	//
	// В REST это выглядит так:
	//
	//	PUT /api/subscriptions/5
	//	Body: { "template_id": 2, "user_id": "...", "start_date": "09-2025", ... }
	UpdateSubscription(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	// --- DELETE /api/subscriptions/{id} ---
	// Удалить подписку по ID.
	// На вход: id.
	// На выход: ничего (Empty).
	//
	// В REST это выглядит так:
	//
	//	DELETE /api/subscriptions/5
	DeleteSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Empty, error)
	// --- GET /api/subscriptions/total-cost ---
	// Рассчитать суммарную стоимость подписок за период.
	// На вход: user_id, service_name (опционально), start_date, end_date.
	// На выход: total (число).
	//
	// В REST это выглядит так:
	//
	//	GET /api/subscriptions/total-cost?user_id=...&start_date=01-2025&end_date=12-2025
	GetTotalCost(ctx context.Context, in *TotalCostRequest, opts ...grpc.CallOption) (*TotalCostResponse, error)
	// --- GET /api/templates ---
	// Получить список всех шаблонов (доступно всем авторизованным пользователям).
	// На вход: ничего (Empty).
	// На выход: список шаблонов (TemplateList).
	ListTemplates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplateList, error)
	// --- GET /api/templates/{id} ---
	// Получить шаблон по ID.
	// На вход: id.
	// На выход: полная запись шаблона (Template).
	GetTemplate(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Template, error)
	// --- POST /api/admin/templates ---
	// Создать новый шаблон (только админ).
	// На вход: service_name, price.
	// На выход: ID созданного шаблона.
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// --- PUT /api/admin/templates/{id} ---
	// Обновить шаблон (только админ).
	// На вход: id + service_name, price.
	// На выход: ничего (Empty).
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*Empty, error)
	// --- DELETE /api/admin/templates/{id} ---
	// Удалить шаблон (только админ).
	// На вход: id.
	// На выход: ничего (Empty).
	DeleteTemplate(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Empty, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionList, error) {
	out := new(SubscriptionList)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CreateSubscription(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CreateSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Subscription, error) {
	out := new(Subscription)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) UpdateSubscription(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubscriptionService_UpdateSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) DeleteSubscription(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubscriptionService_DeleteSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetTotalCost(ctx context.Context, in *TotalCostRequest, opts ...grpc.CallOption) (*TotalCostResponse, error) {
	out := new(TotalCostResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetTotalCost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) ListTemplates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplateList, error) {
	out := new(TemplateList)
	err := c.cc.Invoke(ctx, SubscriptionService_ListTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetTemplate(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Template, error) {
	out := new(Template)
	err := c.cc.Invoke(ctx, SubscriptionService_GetTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CreateTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubscriptionService_UpdateTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) DeleteTemplate(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubscriptionService_DeleteTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	// --- GET /api/subscriptions ---
	// Получить список всех подписок (с пагинацией).
	// На вход: limit (сколько записей), offset (сдвиг от начала).
	// На выход: список подписок (SubscriptionList).
	//
	// В REST это выглядит так:
	//
	//	GET /api/subscriptions?limit=10&offset=0
	GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*SubscriptionList, error)
	// --- POST /api/subscriptions ---
	// Создать новую подписку.
	// На вход: template_id, user_id, start_date, end_date.
	// На выход: ID созданной подписки.
	//
	// В REST это выглядит так:
	//
	//	POST /api/subscriptions
	//	Body: { "template_id": 1, "user_id": "...", "start_date": "08-2025", "end_date": "..." }
	CreateSubscription(context.Context, *CreateRequest) (*CreateResponse, error)
	// --- GET /api/subscriptions/{id} ---
	// Получить одну подписку по её ID.
	// На вход: id.
	// На выход: полная запись подписки (Subscription).
	//
	// В REST это выглядит так:
	//
	//	GET /api/subscriptions/5
	GetSubscription(context.Context, *GetRequest) (*Subscription, error)
	// --- PUT /api/subscriptions/{id} ---
	// Обновить существующую подписку.
	// На вход: id + новые поля.
	// На выход: ничего (Empty), только статус успеха.
	//
	// В REST это выглядит так:
	//
	//	PUT /api/subscriptions/5
	//	Body: { "template_id": 2, "user_id": "...", "start_date": "09-2025", ... }
	UpdateSubscription(context.Context, *UpdateRequest) (*Empty, error)
	// --- DELETE /api/subscriptions/{id} ---
	// Удалить подписку по ID.
	// На вход: id.
	// На выход: ничего (Empty).
	//
	// В REST это выглядит так:
	//
	//	DELETE /api/subscriptions/5
	DeleteSubscription(context.Context, *GetRequest) (*Empty, error)
	// --- GET /api/subscriptions/total-cost ---
	// Рассчитать суммарную стоимость подписок за период.
	// На вход: user_id, service_name (опционально), start_date, end_date.
	// На выход: total (число).
	//
	// В REST это выглядит так:
	//
	//	GET /api/subscriptions/total-cost?user_id=...&start_date=01-2025&end_date=12-2025
	GetTotalCost(context.Context, *TotalCostRequest) (*TotalCostResponse, error)
	// --- GET /api/templates ---
	// Получить список всех шаблонов (доступно всем авторизованным пользователям).
	// На вход: ничего (Empty).
	// На выход: список шаблонов (TemplateList).
	ListTemplates(context.Context, *Empty) (*TemplateList, error)
	// --- GET /api/templates/{id} ---
	// Получить шаблон по ID.
	// На вход: id.
	// На выход: полная запись шаблона (Template).
	GetTemplate(context.Context, *GetRequest) (*Template, error)
	// --- POST /api/admin/templates ---
	// Создать новый шаблон (только админ).
	// На вход: service_name, price.
	// На выход: ID созданного шаблона.
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateResponse, error)
	// --- PUT /api/admin/templates/{id} ---
	// Обновить шаблон (только админ).
	// На вход: id + service_name, price.
	// На выход: ничего (Empty).
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*Empty, error)
	// --- DELETE /api/admin/templates/{id} ---
	// Удалить шаблон (только админ).
	// На вход: id.
	// На выход: ничего (Empty).
	DeleteTemplate(context.Context, *GetRequest) (*Empty, error)
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*SubscriptionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedSubscriptionServiceServer) CreateSubscription(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetSubscription(context.Context, *GetRequest) (*Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) UpdateSubscription(context.Context, *UpdateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) DeleteSubscription(context.Context, *GetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetTotalCost(context.Context, *TotalCostRequest) (*TotalCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalCost not implemented")
}
func (UnimplementedSubscriptionServiceServer) ListTemplates(context.Context, *Empty) (*TemplateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetTemplate(context.Context, *GetRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedSubscriptionServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedSubscriptionServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedSubscriptionServiceServer) DeleteTemplate(context.Context, *GetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetSubscriptions(ctx, req.(*GetSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CreateSubscription(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetSubscription(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).UpdateSubscription(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).DeleteSubscription(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetTotalCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetTotalCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetTotalCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetTotalCost(ctx, req.(*TotalCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).ListTemplates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetTemplate(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).DeleteTemplate(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriptions",
			Handler:    _SubscriptionService_GetSubscriptions_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _SubscriptionService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _SubscriptionService_GetSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _SubscriptionService_UpdateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _SubscriptionService_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetTotalCost",
			Handler:    _SubscriptionService_GetTotalCost_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _SubscriptionService_ListTemplates_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _SubscriptionService_GetTemplate_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _SubscriptionService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _SubscriptionService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _SubscriptionService_DeleteTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/subscription.proto",
}
